#!/usr/bin/env bash

DEVICE="/dev/ttyUSB0"

wait_file() {
  local file="$1"; shift
  until test -e "$file" ; do sleep 1; done
}

echo "Starting CDEM logger"

while true
do
  echo "Checking if device is available ..."

  wait_file "$DEVICE"
  echo "Found CDEM device"

  echo "Starting to log messages"
  cat "$DEVICE" | sed -u '/^$/d' | ts

  echo "Lost the CDEM device"
done