#!/usr/bin/env bash

DEVICE="/dev/ttyUSB0"

wait_file() {
  local file="$1"; shift
  until test -e "$file" ; do sleep 1; done
}

echo "Starting CDEM logger"

while true
do
  wait_file "$DEVICE"
  cat "$DEVICE" | sed -u '/^$/d' | ts
done